# Generated by Django 5.2.15 on 2026-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Python', 'Python'), ('Java', 'Java'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
