# Generated by Django 5.2.15 on 2026-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_freelancerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
