# Generated by Django 5.2.15 on 2026-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_freelancerprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
